[package]
name = "euca"
version = "0.1.0"
authors = ["Matthew Nicholson <matt@matt-land.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies.web-sys]
version = "0.3.6"
features = [
    "Window",
    "Document",
    "Node",
    "Element",
    "Event",
]

[dev-dependencies]
wasm-bindgen-test = "0.2.29"
